<a href="https://colab.research.google.com/github/GustavMartinez/GustavMartinez.github.io/blob/main/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import Numpy Library

In [ ]:
import numpy as np

Para iniciar, se crea un objeto de tipo lista. Este objeto se convierte posteriormente a un objeto de tipo array con Numpy

In [ ]:
lista = [1,2,3,4,5,6,7,8,9]

listArray = np.array(lista)

listArray

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Asi como se puede crear un array, se pueden crear matrizes de multiples dimensiones, por ejemplo la siguiente matriz fue creada y convertida a un array en Numpy

In [ ]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]

matrizArray = np.array(matriz)

matrizArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Indexing** Funciona igual que la extracción de datos en listas normales de python. El primer elemento comienza con el index de 0, si el elemento es una lista, se puede acceder a un elemento dentro de esta adicionando una coma. Ejemplos:

In [ ]:
matrizDeEjemplo = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]]
mtrz = np.array(matrizDeEjemplo)

print(mtrz[0]) #Extrae el elemento de index 0 de la matriz
print(mtrz[1]) #Extrae el elemento de index 1 de la matriz
print(mtrz[2]) #Extrae el elemento de index 2 de la matriz

print(mtrz[0,0]) #Extrae el elemento de index 0 de la lista en index 0
print(mtrz[0,2]) #Extrae el elemento de index 2 de la lista en index 0
print(mtrz[0,4]) #Extrae el elemento de index 4 de la lista en index 0
print(mtrz[1,1]) #Extrae el elemento de index 1 de la lista en index 1
print(mtrz[1,3]) #Extrae el elemento de index 3 de la lista en index 1
print(mtrz[2,4]) #Extrae el elemento de index 4 de la lista en index 2

print(mtrz[0:2]) #Extrae el slicing especificado

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
0
2
4
6
8
14
[[0 1 2 3 4]
 [5 6 7 8 9]]


**Tipos de datos en Numpy** Para ver el tipo de dato creado por Numpy, se utiliza el método dtype

In [ ]:
matrizDeEjemplo = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]] #Definición del Array
mtrz.dtype    #método para identificar el tipo de dato del array

dtype('int64')

To explicitly set the data type of the resulting array, we can use the dtype keyword

In [ ]:
arrayDtype = np.array([0,1,2,3,4], dtype=np.float32) #Primera forma de definir el tipo de dato
arrayDtype2 = np.array([0,1,2,3,4], dtype='float32') #Segunda forma de definir el tipo de dato
arrayDtype.dtype
arrayDtype2.dtype

dtype('float32')

Para convertir un array a un tipo de dato específico, se usa el método "astype":

In [ ]:
lista001 = [0,1,2,3,4]
array001 = np.array(lista001)

array001 = array001.astype(np.float64)

print(array001)

[0. 1. 2. 3. 4.]


De la misma forma, con el paso anterior puedo convertir el array a diferentes tipos de datos.

Posteriormente, tambien es posible identificar el 'shape' del array:

In [ ]:
array001.shape

(5,)